import Airport from '../src/assets/airport.svg'
import Wifi from '../src/assets/wifi.svg'
import Restaurant from '../src/assets/restaurant.svg'
import Pet from '../src/assets/pet.svg'
import Reception from '../src/assets/reception.svg'
import Parking from '../src/assets/parking.svg'
import RoomService from '../src/assets/room-service.svg'
import Gym from '../src/assets/gym.svg'
import Smoking from '../src/assets/smoking.svg'
import Spa from '../src/assets/spa.svg'
import Family from '../src/assets/family.svg'
import Pool from '../src/assets/pool.svg'
export const hotelOptions = { 'Parking' : <img src={Parking} className=''/>, 'Free WiFi' : <img src={Wifi} className='w-8 h-8'/>, 'Restaurant': <img src={Restaurant} className='w-9 h-8'/>, 'Pet Friendly': <img src={Pet} className='w-10 h-10'/>, 'Room Service': <img src={RoomService} className='w-8 h-8'/>, '24-hour frontdesk': <img src={Reception} className='w-9 h-9'/>, 'Gym': <img src={Gym} className='w-10 h-10'/>, 'Airport shuttle': <img src={Airport} className='w-10 h-10'/>, 'Spa': <img src={Spa} className='w-8 h-8'/>,'Swimming Pool': <img src={Pool} className='w-9 h-9'/>}